project:
  type: website
  output-dir: "docs"
website:
  title: "AllôPoto"
  navbar:
    left: 
      - text: Khóa học online
        href: courses.qmd
      - text: Khóa học video
        href: courses-video.qmd
      - text: Blog
        href: blogs.qmd
      - text: Review
        href: feedback.qmd 
    right:
      - icon: whatsapp
        href: https://wa.me/33744192752
      - icon: instagram
        href: https://www.instagram.com/allopoto.be/
      - icon: envelope
        href: mailto:allopoto.be@gmail.com
      - icon: facebook
        href: https://facebook.com/allopoto.vn
      - icon: tiktok
        href: https://www.tiktok.com/@allopoto.be
format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss

editor: visual

